### PR TITLE
Issue/159 yesnotobool converting rule

### PR DESCRIPTION
**Pull request by HoePe999**
### Fixed Issues (if relevant)

1. magento/async-import#159:Create "YesNoToBool" converting rule

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/async-import?pullRequest=189) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/async-import?pullRequest=189) before we can accept your contribution.<br/><hr/>**Peter Höcherl** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by HoePe999** [comment]
(!) Adds a setter-method to \Magento\AsynchronousImportApi\Api\Data\ImportDataInterface and implements it in \Magento\AsynchronousImport\Model\Import\ImportData
This method is needed to allow changes on the import data (array)

**Comment by nuzil** [comment]
Thanks a lot for contribution! 
Let us validate PR #191 and then we will check this one, cause you are the first one who made a new Rule, so we may need to define etalon Rule based on your one :-)

**Comment by naydav** [comment]
@HoePe999 @HoePe999 
I merged the last mainline and updated code according to changes.
Thanks

**Comment by naydav** [comment]
@HoePe999
Hello Peter,
Can you accept CLA?
I'm going to merge your PR
Thanks

**Pull request merged**
