### PR TITLE
ASYNC-IMPORT:37 Implement DB operation for save source endpoints

### PR DESCRIPTION
**Pull request by Stepa4man**
### Description (*)
Implemented saving source to db

### Fixed Issue
magento/async-import#37: Implement DB operation for save source endpoints

### Manual testing scenarios (*)
Manually can't be tested

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/async-import?pullRequest=41) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/async-import?pullRequest=41) before we can accept your contribution.<br/>

**Comment by nuzil** [comment]
Closed and reopened trying to restart tests

**Comment by nuzil** [comment]
@Stepa4man can you pls. sign Agreement?

**Comment by Stepa4man** [comment]
@nuzil, done

**Comment by nuzil** [comment]
Can you please fix statics? 

```
FILE: ...app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
----------------------------------------------------------------------
FOUND 10 ERRORS AFFECTING 10 LINES
----------------------------------------------------------------------
 17 | ERROR | [x] Missing short description
 18 | ERROR | [x] There must be exactly one blank line before tags
 23 | ERROR | [x] Missing short description
 24 | ERROR | [x] There must be exactly one blank line before tags
 29 | ERROR | [x] Missing short description
 30 | ERROR | [x] There must be exactly one blank line before tags
 35 | ERROR | [x] Missing short description
 36 | ERROR | [x] There must be exactly one blank line before tags
 41 | ERROR | [x] Missing short description
 42 | ERROR | [x] There must be exactly one blank line before tags
----------------------------------------------------------------------
PHPCBF CAN FIX THE 10 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

FILE: ...ml/app/code/Magento/ImportService/Model/ResourceModel/Source.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 20 | ERROR | Comment block is missing
----------------------------------------------------------------------

FILE: .../Magento/ImportService/Model/ResourceModel/Source/Collection.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 19 | ERROR | Comment block is missing
----------------------------------------------------------------------

FILE: /var/www/html/app/code/Magento/ImportService/Model/Source.php
----------------------------------------------------------------------
FOUND 8 ERRORS AFFECTING 8 LINES
----------------------------------------------------------------------
  21 | ERROR | [ ] Comment block is missing
  26 | ERROR | [x] Missing short description
  27 | ERROR | [x] There must be exactly one blank line before tags
  34 | ERROR | [x] Missing short description
  35 | ERROR | [x] There must be exactly one blank line before tags
 115 | ERROR | [x] If the @inheritdoc not inline it shouldn’t have
     |       |     braces
 125 | ERROR | [x] If the @inheritdoc not inline it shouldn’t have
     |       |     braces
 130 | ERROR | [ ] Line exceeds maximum limit of 120 characters;
     |       |     contains 121 characters
----------------------------------------------------------------------
PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY

FILE: ...w/html/app/code/Magento/ImportService/Model/SourceRepository.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 68 | ERROR | [x] There must be exactly one blank line between lines
 83 | ERROR | [x] There must be exactly one blank line between lines
 98 | ERROR | [x] There must be exactly one blank line between lines
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

```

**Pull request merged**
