### PR TITLE
Add OperationStatusPool and OperationStatusValidator

### PR DESCRIPTION
**Pull request by sedonik**
### Description

Added Magento\AsynchronousOperations\Model\OperationStatusPool and Magento\AsynchronousOperations\Model\OperationStatusValidator classes. 
Added list of statuses to Magento\AsynchronousOperations\Model\OperationStatusPool with di.xml file.
Added validation to Magento\AsynchronousOperations\Model\Operation::setStatus method. 

### Fixed Issues

1. magento/async-import#100: Add Operation Status validator

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nuzil** [comment]
Thanks a lot for your PR. I will wait till we have tests ready on this Repo and will review it

**Comment by slavvka** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
Hi @sedonik 
Sorry for a late review.
Will it be possible to cover it with tests?

**Comment by sedonik** [comment]
Hi @nuzil ,
Thanks for the response. I will.

**Comment by naydav** [comment]
@nuzil 
Please move this PR to https://github.com/magento/magento2/pulls if it's still actual
Also, need to move the corresponding ticket to https://github.com/magento/community-features for a feature request
or in https://github.com/magento/magento2/issues for a bug
Thanks

**Comment by nuzil** [comment]
@sedonik will it be possible for you to open same PR in magento/magento2 repository ?

**Comment by sedonik** [comment]
Hi @nuzil,
I've updated the code with Unit Test. 
Could you check, please?
Thanks.

**Comment by nuzil** [comment]
you can mark me there, I will confirm it. Implementation looks good for me

**Pull request closed without merging**
